# -------- Build stage --------
FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app

# (optionnel mais accélère) cache dépendances
COPY pom.xml .
RUN mvn -B -q -DskipTests dependency:go-offline

# build
COPY src ./src
RUN mvn -B -DskipTests clean package

# -------- Run stage --------
FROM eclipse-temurin:17-jre
WORKDIR /app

# Copie le jar produit (si ton jar a un nom fixe, adapte si besoin)
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]
